# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'peer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeer.proto\x12\x04peer\"9\n\x0fGetPieceRequest\x12\x11\n\tinfo_hash\x18\x01 \x01(\t\x12\x13\n\x0bpiece_index\x18\x02 \x01(\x05\"\x19\n\tPieceData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\")\n\x14GetHavePiecesRequest\x12\x11\n\tinfo_hash\x18\x01 \x01(\t\"%\n\x15GetHavePiecesResponse\x12\x0c\n\x04have\x18\x01 \x03(\x05\x32\x86\x01\n\x04Peer\x12\x34\n\x08GetPiece\x12\x15.peer.GetPieceRequest\x1a\x0f.peer.PieceData0\x01\x12H\n\rGetHavePieces\x12\x1a.peer.GetHavePiecesRequest\x1a\x1b.peer.GetHavePiecesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPIECEREQUEST']._serialized_start=20
  _globals['_GETPIECEREQUEST']._serialized_end=77
  _globals['_PIECEDATA']._serialized_start=79
  _globals['_PIECEDATA']._serialized_end=104
  _globals['_GETHAVEPIECESREQUEST']._serialized_start=106
  _globals['_GETHAVEPIECESREQUEST']._serialized_end=147
  _globals['_GETHAVEPIECESRESPONSE']._serialized_start=149
  _globals['_GETHAVEPIECESRESPONSE']._serialized_end=186
  _globals['_PEER']._serialized_start=189
  _globals['_PEER']._serialized_end=323
# @@protoc_insertion_point(module_scope)
