# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tracker_pb2 as tracker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tracker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Hello = channel.unary_unary(
                '/tracker.Tracker/Hello',
                request_serializer=tracker__pb2.HelloRequest.SerializeToString,
                response_deserializer=tracker__pb2.HelloResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/tracker.Tracker/Heartbeat',
                request_serializer=tracker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=tracker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.PublishTorrent = channel.unary_unary(
                '/tracker.Tracker/PublishTorrent',
                request_serializer=tracker__pb2.PublishTorrentRequest.SerializeToString,
                response_deserializer=tracker__pb2.PublishTorrentResponse.FromString,
                _registered_method=True)
        self.ListTorrents = channel.unary_unary(
                '/tracker.Tracker/ListTorrents',
                request_serializer=tracker__pb2.ListTorrentsRequest.SerializeToString,
                response_deserializer=tracker__pb2.ListTorrentsResponse.FromString,
                _registered_method=True)
        self.GetTorrent = channel.unary_unary(
                '/tracker.Tracker/GetTorrent',
                request_serializer=tracker__pb2.GetTorrentRequest.SerializeToString,
                response_deserializer=tracker__pb2.GetTorrentResponse.FromString,
                _registered_method=True)
        self.Announce = channel.unary_unary(
                '/tracker.Tracker/Announce',
                request_serializer=tracker__pb2.AnnounceRequest.SerializeToString,
                response_deserializer=tracker__pb2.AnnounceResponse.FromString,
                _registered_method=True)
        self.GetPeers = channel.unary_unary(
                '/tracker.Tracker/GetPeers',
                request_serializer=tracker__pb2.GetPeersRequest.SerializeToString,
                response_deserializer=tracker__pb2.GetPeersResponse.FromString,
                _registered_method=True)
        self.UpdateProgress = channel.unary_unary(
                '/tracker.Tracker/UpdateProgress',
                request_serializer=tracker__pb2.UpdateProgressRequest.SerializeToString,
                response_deserializer=tracker__pb2.UpdateProgressResponse.FromString,
                _registered_method=True)
        self.GetProgress = channel.unary_unary(
                '/tracker.Tracker/GetProgress',
                request_serializer=tracker__pb2.GetProgressRequest.SerializeToString,
                response_deserializer=tracker__pb2.GetProgressResponse.FromString,
                _registered_method=True)


class TrackerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Hello(self, request, context):
        """Registro general del peer (no depende de torrents)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishTorrent(self, request, context):
        """Catálogo de torrents en el tracker
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTorrents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTorrent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Announce(self, request, context):
        """Lo de antes (por torrent)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Hello': grpc.unary_unary_rpc_method_handler(
                    servicer.Hello,
                    request_deserializer=tracker__pb2.HelloRequest.FromString,
                    response_serializer=tracker__pb2.HelloResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=tracker__pb2.HeartbeatRequest.FromString,
                    response_serializer=tracker__pb2.HeartbeatResponse.SerializeToString,
            ),
            'PublishTorrent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTorrent,
                    request_deserializer=tracker__pb2.PublishTorrentRequest.FromString,
                    response_serializer=tracker__pb2.PublishTorrentResponse.SerializeToString,
            ),
            'ListTorrents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTorrents,
                    request_deserializer=tracker__pb2.ListTorrentsRequest.FromString,
                    response_serializer=tracker__pb2.ListTorrentsResponse.SerializeToString,
            ),
            'GetTorrent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTorrent,
                    request_deserializer=tracker__pb2.GetTorrentRequest.FromString,
                    response_serializer=tracker__pb2.GetTorrentResponse.SerializeToString,
            ),
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=tracker__pb2.AnnounceRequest.FromString,
                    response_serializer=tracker__pb2.AnnounceResponse.SerializeToString,
            ),
            'GetPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeers,
                    request_deserializer=tracker__pb2.GetPeersRequest.FromString,
                    response_serializer=tracker__pb2.GetPeersResponse.SerializeToString,
            ),
            'UpdateProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProgress,
                    request_deserializer=tracker__pb2.UpdateProgressRequest.FromString,
                    response_serializer=tracker__pb2.UpdateProgressResponse.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=tracker__pb2.GetProgressRequest.FromString,
                    response_serializer=tracker__pb2.GetProgressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracker.Tracker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracker.Tracker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tracker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Hello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/Hello',
            tracker__pb2.HelloRequest.SerializeToString,
            tracker__pb2.HelloResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/Heartbeat',
            tracker__pb2.HeartbeatRequest.SerializeToString,
            tracker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishTorrent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/PublishTorrent',
            tracker__pb2.PublishTorrentRequest.SerializeToString,
            tracker__pb2.PublishTorrentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTorrents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/ListTorrents',
            tracker__pb2.ListTorrentsRequest.SerializeToString,
            tracker__pb2.ListTorrentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTorrent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/GetTorrent',
            tracker__pb2.GetTorrentRequest.SerializeToString,
            tracker__pb2.GetTorrentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/Announce',
            tracker__pb2.AnnounceRequest.SerializeToString,
            tracker__pb2.AnnounceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/GetPeers',
            tracker__pb2.GetPeersRequest.SerializeToString,
            tracker__pb2.GetPeersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/UpdateProgress',
            tracker__pb2.UpdateProgressRequest.SerializeToString,
            tracker__pb2.UpdateProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.Tracker/GetProgress',
            tracker__pb2.GetProgressRequest.SerializeToString,
            tracker__pb2.GetProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
